### ISSUE TITLE
CPU support ?

### ISSUE THREAD

**Issue by hsakas** [shrubb/box-convolutions#10]
Thanks for the code, 

I opened an issue for the following reason.
1) Fails to install in CPU only environment, here is the complete traceback:

I just want to check the input-output with very low dimension tensors and check the working of the model. Is it possible to get a CPU support for this? 

(Torch) C:\Users\as\Documents\Workspace\Experiments\BoxCon\box-convolutions>python -m pip install .
Processing c:\users\as\documents\workspace\experiments\boxcon\box-convolutions
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\AKASHS~1\AppData\Local\Temp\pip-req-build-amptjpk7\setup.py", line 2, in <module>
        import torch.utils.cpp_extension
      File "C:\Users\as\Anaconda3\envs\Torch\lib\site-packages\torch\utils\cpp_extension.py", line 61, in <module>
        CUDA_HOME = _find_cuda_home()
      File "C:\Users\as\Anaconda3\envs\Torch\lib\site-packages\torch\utils\cpp_extension.py", line 30, in _find_cuda_home
        if not os.path.exists(cuda_home):
      File "C:\Users\as\Anaconda3\envs\Torch\lib\genericpath.py", line 19, in exists
        os.stat(path)
    TypeError: stat: path should be string, bytes, os.PathLike or integer, not list

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\AKASHS~1\AppData\Local\Temp\pip-req-build-amptjpk7\

**Comment by shrubb** [comment]
You seem have an old version of PyTorch with this bug: pytorch/pytorch#11137. I've also updated my repository to support CPU-only platforms. So, please update both and let me know if that worked.

**Comment by hsakas** [comment]
thanks, will confirm it.
