### ISSUE TITLE
Getting a cuda runtime error (9) : invalid configuration argument at src/box_convolution_cuda_forward.ci:250

### ISSUE THREAD

**Issue by dkang9503** [shrubb/box-convolutions#22]
Hello,

I've been trying to implement your box convolution layer on a ResNet model by just substituting your BottleneckBoxConv layers for a typical ResNet Bottleneck layer. 

I was getting this error

```
THCudaCheck FAIL file=src/box_convolution_cuda_forward.cu line=250 error=9 : invalid configuration argument
Traceback (most recent call last):
  File "half_box_train.py", line 178, in <module>
    main()
  File "half_box_train.py", line 107, in main
    scores = res_net(x)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dkang/Project/cs231n_project_box_convolution/models/HalfBoxResNet.py", line 331, in forward
     x = self.layer3(x)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
       input = module(input)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dkang/Project/cs231n_project_box_convolution/models/HalfBoxResNet.py", line 66, in forward
    return F.relu(x + self.main_branch(x), inplace=True)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
input = module(input)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/box_convolution/box_convolution_module.py", line 222, in forward
    self.reparametrization_h, self.reparametrization_w, self.normalize, self.exact)
  File "/opt/anaconda3/lib/python3.7/site-packages/box_convolution/box_convolution_function.py", line 46, in forward
    input_integrated, x_min, x_max, y_min, y_max, normalize, exact)
RuntimeError: cuda runtime error (9) : invalid configuration argument at src/box_convolution_cuda_forward.cu:250
```
Thanks so much!

**Comment by shrubb** [comment]
Can you give a minimal script to reproduce? What are that layer's configuration, its input tensor size? What are your GPU, CUDA version?

**Comment by dkang9503** [comment]
Sorry for the late response

We are trying to recreate resnet with box convolutions instead of the 3x3 Conv2d layers

This code throws an error for me

```
import torch
import torchvision
import torch.nn as nn
import torchvision.transforms as transforms
from box_convolution import BoxConv2d

cifar = torchvision.datasets.CIFAR10("./data/", transform = transforms.ToTensor())
cifar_train = torch.utils.data.DataLoader(cifar, batch_size = 256, shuffle = True)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

box_net = nn.Sequential(
    nn.Conv2d(3, 64, kernel_size = 7, stride = 2, padding = 3, bias = False), #Initial Convolution
    nn.BatchNorm2d(64),
    nn.ReLU(inplace = True),
    nn.MaxPool2d(kernel_size = 3, stride = 2, padding = 1),
    nn.Conv2d(64, 64, 1, 1), #LAYER 1 BN0
    nn.BatchNorm2d(64),
    BoxConv2d(64, 4, 16//2, 16//2, 1.5625)
)
box_net.to(device)

sample_x, sample_y = next(iter(cifar_train))
sample_x = sample_x.to(device = device)
sample_y = sample_y.to(device = device)

ex = box_net(sample_x)
```

We are trying to use this for Tiny ImageNet, but for this example here, we use CIFAR10 with input dimensions 256 x 3 x 32 x 32.

I've found that the code runs if we replace the number of boxes from 4 to 3, but then if we add another BoxConvolution on top of that, it crashes no matter the dimensions.

For example
```
box_net = nn.Sequential(
    nn.Conv2d(3, 64, kernel_size = 7, stride = 2, padding = 3, bias = False), #Initial Convolution
    nn.BatchNorm2d(64),
    nn.ReLU(inplace = True),
    nn.MaxPool2d(kernel_size = 3, stride = 2, padding = 1),
    nn.Conv2d(64, 64, 1, 1), #LAYER 1 BN0
    nn.BatchNorm2d(64),
    BoxConv2d(64, 3, 16//2, 16//2, 1.5625), 
    nn.BatchNorm2d(3*64),
    nn.Conv2d(3 * 64, 256, 1, 1),
    nn.BatchNorm2d(256),
    nn.ReLU(inplace = True),
    nn.Conv2d(256, 64, 1, 1), #LAYER 1 BN1
    nn.BatchNorm2d(64),
    BoxConv2d(64, 3, 16//2, 16//2, 1.5625)
)
box_net.to(device)
```

This is being done on Google cloud with the following GPU/CUDA

![image](https://user-images.githubusercontent.com/23044451/58388731-71799380-7fd7-11e9-87a7-fd2251c5ab74.png)

**Comment by dkang9503** [comment]
I think I've figured out why it crashes?

It seems as if there's more than 255 boxes, the function always throws this error. Is there a possible workaround for this? Or is it because there's no reason to have that many boxes

**Comment by shrubb** [comment]
This is a known problem, the total number of output pixels is limited to 2^31-1. Let me fix this in the next few days.
In your case, a temporary workaround can be using a smaller batch.

Your second example, however, is more intricate. I'm not sure why it crashes. I'll look deeper into it.

**Comment by shrubb** [comment]
OK, I found out that the total number of channels (batch size * in_channels * out_channels) was limited to 65535. Now fixed.
